---
title: "Predição 02 dados de 22 abril 2021"
author: "José Elvano Moraes"
date: "4/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r libraries, echo=FALSE}
suppressPackageStartupMessages(expr = library(tidyverse))
suppressPackageStartupMessages(expr = library(haven))
suppressPackageStartupMessages(expr = library(bnlearn))
suppressPackageStartupMessages(expr = library(Rgraphviz))
suppressPackageStartupMessages(expr = library(gRain))
suppressPackageStartupMessages(expr = library(Rmpfr))
suppressPackageStartupMessages(expr = library(readr))
suppressPackageStartupMessages(expr = library(precrec))
suppressPackageStartupMessages(expr = library(ROCR))
suppressPackageStartupMessages(expr = library(epiR))
suppressPackageStartupMessages(expr = library(ROCit))
suppressPackageStartupMessages(expr = library(mice))
suppressPackageStartupMessages(expr = library(ROCit))
suppressPackageStartupMessages(expr = library(readr))
suppressPackageStartupMessages(expr = library(cvms))
suppressPackageStartupMessages(expr = library(broom))    # tidy()
suppressPackageStartupMessages(expr = library(tibble))   # tibble()
```

```{r}
INFLUD21_12_04_2021 <- readRDS('./dados/INFLUD21_12_04_2021.rds')
```


```{r}
colunas <- c("CLASSI_FIN", 
             "SEM_NOT", 
             "DT_SIN_PRI", 
             #"DT_NASC", 
             "TP_IDADE",
             "SG_UF_NOT",
             #"CO_MUN_RES", 
             #"DT_NOTIFIC",      
             "NU_IDADE_N",
             #"FEBRE",
             #"GARGANTA",
             "SATURACAO", 
             #"VOMITO",
             "EVOLUCAO",
             "DIABETES",
             "OBESIDADE", 
             "TOMO_RES",
             #"CS_GESTANT",
             "DOR_ABD", 
             #"DT_EVOLUCA", 
             #"CS_RACA", 
             #"CS_SEXO",
             "PERD_OLFT", 
             "PERD_PALA", 
             #"NEUROLOGIC", 
             #"FADIGA", 
             #"CRITERIO",
             "PNEUMOPATI", 
             "UTI", 
             "CARDIOPATI", 
             "VACINA", 
             "HOSPITAL",
             #"HEPATICA",
             "SUPORT_VEN", 
             "ASMA",
             #"ANTIVIRAL", 
             "IMUNODEPRE",
             "OUTRO_SIN"
             #"RENAL"#, 
             #"DT_INTERNA"
             )

dd.with.na <- INFLUD21_12_04_2021[, colunas]
```


# dados contendo NA´s
```{r}
glimpse(dd.with.na)
```

# Dados com NA´s omitidos
```{r}
dd.without.na <- na.omit(dd.with.na)
glimpse(dd.without.na)
```

## São paulo somente
```{r}
#separar grupo de variaveis para analise

ddf <- dd.with.na %>%
  rename(IDADE = NU_IDADE_N) %>%
  filter(SG_UF_NOT == "SP") %>%
  na.omit(ddf) %>%
  filter(TP_IDADE == 3) %>%
  filter(CLASSI_FIN == 5) %>%
  mutate_if(is.double, as.factor)  %>%
  mutate_if(is.character, as.factor) %>%
  select(-TP_IDADE, -DT_SIN_PRI, -CLASSI_FIN)

# dat <- dat %>%
#     mutate(
#         Smoking = as.factor(Smoking),
#         Education = as.factor(Education),
#         Cholesterol = as.numeric(Cholesterol)
#     )

ddf$IDADE = as.double(ddf$IDADE)
  
# discretize idade
ddf <- discretize(ddf, method = 'interval') 
ddf <- as.data.frame(ddf)

glimpse(ddf)
```


```{r}
nn <- nrow(ddf)

n.test <- round(0.9*nrow(ddf))
n.learn <-  nn - n.test

ii.learn <- sample(x = 1:nn, size = n.learn, replace = FALSE)
ddf$index = 'T'
ddf$index[ii.learn] <- 'L'
table(ddf$index)
```


```{r}
# train
s1 <- ddf %>% 
  filter(index == "L") 
s1 <- select(ddf, -index, -SG_UF_NOT, -HOSPITAL)
s1 <- as.data.frame(s1)

# test
s2 <- ddf %>%
  filter(index=="T")
s2 <- select(ddf, -index, -SG_UF_NOT, -HOSPITAL)
s2 <- as.data.frame(s2)
```

```{r}
set.seed(4242)
```

```{r}
wl <- matrix(c("OBESIDADE", "DIABETES",
              "IDADE", "VACINA",
              "IDADE", "SUPORT_VEN",
              #"CLASSI_FIN", "EVOLUCAO",
              "OBESIDADE", "EVOLUCAO",
              "OBESIDADE", "EVOLUCAO",
              "PERD_OLFT", "SATURACAO",
              "SUPORT_VEN", "EVOLUCAO",
              "SATURACAO", "SUPORT_VEN",
              "IDADE","EVOLUCAO",
              "UTI", "EVOLUCAO"),
        ncol = 2, byrow = TRUE, dimnames = list(NULL, c("from", "to")))

bl <- matrix(c("OBESIDADE", "DIABETES",
               #"OBESIDADE", "CLASSI_FIN",
               #"CLASSI_FIN", "OBESIDADE",
               "UTI", "VACINA"),
            ncol = 2, byrow = TRUE, dimnames = list(NULL, c("from", "to")))
```

```{r}
bn.hc   <- suppressWarnings(hc(s1, whitelist = wl, blacklist = bl))
bn.mmhc <- suppressWarnings(mmhc(s1, whitelist = wl, blacklist = bl))
bn.gs   <- suppressWarnings(gs(s1, whitelist = wl, blacklist = bl))
bn.iamb <- suppressWarnings(iamb(s1, whitelist = wl, blacklist = bl))

par(mfrow = c(1, 2))
graphviz.plot(bn.hc, 
              shape = 'rectangle', 
              main = "Algo = HC",
              highlight  = list(nodes = mb(bn.hc, 'EVOLUCAO')))
graphviz.plot(bn.mmhc, 
              shape = 'rectangle', 
              main = "Algo = MMHC",
              highlight  = list(nodes = mb(bn.mmhc, 'EVOLUCAO')))

par(mfrow = c(1, 2))
graphviz.plot(bn.gs, 
              shape = 'rectangle', 
              main = "Algo = GS",
              highlight  = list(nodes = mb(bn.gs, 'EVOLUCAO')))
graphviz.plot(bn.iamb, 
              shape = 'rectangle', 
              main = "Algo = IAMB",
              highlight  = list(nodes = mb(bn.iamb, 'EVOLUCAO')))
```


------------


# Predição 


## Bootstrap REDE PADRÃO

```{r}
boots.trap <- 100
start_time <- Sys.time()
forca.real <- suppressWarnings(boot.strength(s1,
                               R = boots.trap, 
                               algorithm = "hc"))


rede.media.s1 = averaged.network(forca.real)

thr.real <- paste('Thr: ', attr(forca.real, "threshold"))

delta <- Sys.time() - start_time
cat(paste("Tempo para ", boots.trap, "Bootstraps:", delta, "s"))
```

## Rede "dagged"
```{r}
rede.media.s1.dagged <- pdag2dag(rede.media.s1, 
                                   ordering = names(s1))
```

```{r}
par(mfrow = c(1, 2))
graphviz.plot(bn.hc, 
              shape = "rectangle", 
              main = paste(thr.real),
              highlight = list(nodes = mb(bn.iamb, 'EVOLUCAO')))
strength.plot(rede.media.s1, 
              forca.real, 
              shape = "rectangle", 
              main = paste(thr.real), 
              highlight = list(nodes = mb(bn.iamb, 'EVOLUCAO')))
```



# SET.EVIDENCE + QUERYGRAIN
```{r echo=TRUE}
# 
# [1] "CLASSI_FIN" "IDADE" "OBESIDADE"  "UTI"  "SUPORT_VEN" 
# 

# IDADE
# [1,36] (36,71] (71,106]

# UTI
#  1-Sim 
#  2-Nao 
#  9-Ignorado

#SUPORT_VEN
# 1-Sim, invasivo 
# 2-Sim, nao invasivo 
# 3-Nao
# 9-Ignorado
# 
prediga <- function(rede, amostras, estados){
  
  fitt1 <- bn.fit(rede, amostras)
  junction = compile(as.grain(fitt1))
  jedu = setEvidence(propagate = TRUE, junction,
                     node = c(#"CLASSI_FIN",
                              "IDADE",
                              "OBESIDADE",
                              "UTI",
                              "SUPORT_VEN"),
                     states =  estados)
  pred.rede <- querygrain(jedu,
                          nodes = c("EVOLUCAO"),
                          type = "marginal")
  return(pred.rede)
}

estados <- c("(36,71]", "1", "2", "3")

pred.rede <- prediga(bn.hc, s1, estados)


print(pred.rede)
```



```{r echo=TRUE}
# usando dataset de test
x <- filter(s2, 
            #CLASSI_FIN == 5, 
            IDADE == "(36,71]", 
            OBESIDADE == 1, 
            UTI == 2, 
            SUPORT_VEN == 3)
pred.proporcao <- nrow(filter(x, EVOLUCAO == 1))/nrow(x)

print(pred.proporcao)
```
# Fit dag to data and predict the value of latent variable

```{r}
train <- s1
test <- s2

training  <- bn.fit(bn.hc, train)
```


## predicting a variable in the test set. UTI
```{r}
predicted  <- predict(training,  
                      node = "UTI", 
                      data = test, 
                      method = "bayes-lw")
test$PREDICAO  <- predicted

test <- na.omit(test)

conf_mat.uti  <- confusion_matrix(targets = test$UTI,
                                  predictions = test$PREDICAO)

par(mfrow = c(1, 1))
plot_confusion_matrix(conf_mat.uti$`Confusion Matrix`[[1]])
```

## predicting a variable in the test set. EVOLUCAO
```{r}
predicted  <- predict(training,  
                      node = "EVOLUCAO", 
                      data = test, 
                      method = "bayes-lw")

test$PREDICAO  <- predicted
test <- na.omit(test)

conf_mat.evolucao  <- confusion_matrix(targets = test$EVOLUCAO,
                                       predictions = test$PREDICAO)

par(mfrow = c(1, 1))
plot_confusion_matrix(conf_mat.evolucao$`Confusion Matrix`[[1]])

```
## predicting a variable in the test set. TOMO_RES
```{r}
predicted  <- predict(training,  
                      node = "TOMO_RES", 
                      data = test, 
                      method = "bayes-lw")

test$PREDICAO  <- predicted
test <- na.omit(test)

conf_mat.tomo.res  <- confusion_matrix(targets = test$TOMO_RES,
                                       predictions = test$PREDICAO)

par(mfrow = c(1, 1))
plot_confusion_matrix(conf_mat.tomo.res$`Confusion Matrix`[[1]])

```
